set more off
graph drop _all

***For generating figures 4 and A3.  Uses data transitions-by-group.dta as generated by transitions-by-group.do

use "\\tsclient\G\research\brookings-dynamism\output\pub\transitions-by-groups.dta", clear
keep if year>=1976

foreach v in empchange Estar starE UE NE EN EU {
if "`v'"=="Estar" local title="Job separation rate"
if "`v'"=="starE" local title="Job finding rate"
if "`v'"=="empchange" local title="Fraction of employed with 2+ employers in prev. year"
if "`v'"=="EU" local title="EU transition rate"
if "`v'"=="EN" local title="EN transition rate"
if "`v'"=="UE" local title="UE transition rate"
if "`v'"=="NE" local title="NE transition rate"

# delimit ;
twoway 
(connected `v' year if status=="all", lcolor(black) lwidth(medthick) lpattern(solid) msymbol(none) msize(small) mcolor(black))
(connected `v' year if status=="16-24", lcolor(maroon) lwidth(medthick) lpattern(dot) msymbol(none) msize(small) mcolor(maroon))
(connected `v' year if status=="55+", lcolor(navy) lwidth(medthick) lpattern(dash) msymbol(none) msize(small) mcolor(navy))
(connected `v' year if status=="male", lcolor(orange) lwidth(medthin) lpattern(solid) msymbol(O) msize(small) mcolor(orange))
(connected `v' year if status=="female", lcolor(green) lwidth(medthin) lpattern(solid) msymbol(X) msize(small) mcolor(green))
,
legend(order (1 "all" 2 "16-24" 3 "55+" 4 "Males, 25-54" 5 "Female, 25-54") rows(3) size(vsmall) region(style(none)))
xlabel(1975(5)2015, labsize(vsmall)) 
xmlabel(1975(1)2015, nolab)
xtitle("")
ytitle("")
ylabel(, nogrid labsize(vsmall))
graphregion(fcolor(white) lcolor(white) ifcolor(white) ilcolor(white) margin(small)) 
plotregion(fcolor(white) lcolor(white) ifcolor(white) ilcolor(white) margin(small))
title("`title'", size(small) )
saving("\\tsclient\G\research\brookings-dynamism\output\pub\trends-levels-`v'.gph", replace)
name(`v', replace);

# delimit cr

}

foreach v in migstate {
gen d_`v'=.
foreach status in "all" "16-24" "25-54" "55+" "male" "female" {
sum `v' if status=="`status'" & year==1981
replace d_`v'=`v'-`r(mean)' if status=="`status'"
}
# delimit ;
twoway 
(connected `v' year if status=="all" & year!=1985 & year!=1990, lcolor(black) lwidth(medthick) lpattern(solid) msymbol(none) msize(small) mcolor(black))
(connected `v' year if status=="16-24" & year!=1985 & year!=1990, lcolor(maroon) lwidth(medthick) lpattern(dot) msymbol(none) msize(small) mcolor(maroon))
(connected `v' year if status=="55+" & year!=1985 & year!=1990, lcolor(navy) lwidth(medthick) lpattern(dash) msymbol(none) msize(small) mcolor(navy))
(connected `v' year if status=="male" & year!=1985 & year!=1990, lcolor(orange) lwidth(medthin) lpattern(solid) msymbol(O) msize(small) mcolor(orange))
(connected `v' year if status=="female" & year!=1985 & year!=1990, lcolor(green) lwidth(medthin) lpattern(solid) msymbol(X) msize(small) mcolor(green))
,
legend(order (1 "all" 2 "16-24" 3 "55+" 4 "Males, 25-54" 5 "Female, 25-54") rows(3) size(vsmall) region(style(none)))
xlabel(1975(5)2015, labsize(vsmall)) 
xmlabel(1975(1)2015, nolab)
xtitle("")
ytitle("")
ylabel(, nogrid labsize(vsmall))
graphregion(fcolor(white) lcolor(white) ifcolor(white) ilcolor(white) margin(small)) 
plotregion(fcolor(white) lcolor(white) ifcolor(white) ilcolor(white) margin(small))
title("Fract. changing states in prev. year", size(small))
saving("\\tsclient\G\research\brookings-dynamism\output\pub\trends-levels-`v'.gph", replace)
name(`v', replace);

# delimit cr

}
